const issuesJson = {
  NexusIqIssues: [
    {
      "Assignment Group": "Authentication",
      Threat: 10,
      Policy: "Security-Critical-Banned",
      Component: "org.springframework : spring-web flux : 5.3.31",
      "Policy Violations": "Found security vulnerabilities CVE-2024-11111",
      "Risk Remediations": "Upgrade to 6.1.14",
    },
    {
      "Assignment Group": "Login",
      Threat: 10,
      Policy: "Security-Critical-Banned",
      Component: "org.springframework : spring-webmvc: 5.3.31",
      "Policy Violations": "Found security vulnerabilities CVE-2024-11112",
      "Risk Remediations": "Upgrade to 6.1.12",
    },
    {
      "Assignment Group": "SSO",
      Threat: 8,
      Policy: "Security-High-Warning",
      Component: "io.micrometer : micrometer-registry-statsd",
      "Policy Violations": "Found security vulnerabilities CVE-2024-11113",
      "Risk Remediations": "Upgrade to 6.1.16",
    },
  ],
  Vulnerabilities: [
    {
      "Assignment Group": "Authentication",
      State: "Open",
      VIT: "VIT123",
      "Risk Rating": "Critical",
      Summary:
        "This could allow the attacker with control over Thread context map",
      Results: "org.apache.logging.log4j",
      "Configuration Item": "login-api",
      "Remediation Target": "2024-12-31",
    },
    {
      "Assignment Group": "Login",
      State: "Open",
      VIT: "VIT456",
      "Risk Rating": "Moderate",
      Summary:
        "Component has got apache vulnerability making it prone to attack",
      Results: "org.apache.logging.log4j.log4j",
      "Configuration Item": "mobile-api",
      "Remediation Target": "2024-12-31",
    },
    {
      "Assignment Group": "SSO",
      State: "Progress",
      VIT: "VIT789",
      "Risk Rating": "Critical",
      Summary: "Spring version is not safe for threads",
      Results: "org.eclipse.jetty.http2",
      "Configuration Item": "login-ui",
      "Remediation Target": "2024-12-31",
    },
  ],
  RiskUnits: [
    {
      "Assignment Group": "Authentication",
      State: "Open",
      RiskID: 123,
      "Detection Source": "Standard Assurance",
      "Detection Method": "Assessment",
      "Submitted by": "Gurjot",
      "Submit Date": "2024-11-10",
      "Remediation Due Date": "2024-12-31",
      Title: "mobile encryption",
      Description: "code has some vulnerabilities",
    },
    {
      "Assignment Group": "Login",
      State: "Open",
      RiskID: 456,
      "Detection Source": "Standard Assurance",
      "Detection Method": "Assessment",
      "Submitted by": "Venkat",
      "Submit Date": "2024-11-12",
      "Remediation Due Date": "2024-12-31",
      Title: "mobile encryption",
      Description: "code has some vulnerabilities",
    },
    {
      "Assignment Group": "SSO",
      State: "Progress",
      RiskID: 789,
      "Detection Source": "Standard Assurance",
      "Detection Method": "Assessment",
      "Submitted by": "San",
      "Submit Date": "2024-11-15",
      "Remediation Due Date": "2024-12-31",
      Title: "mobile encryption",
      Description: "code has some vulnerabilities",
    },
  ],
  Security: [
    {
      "Assignment Group": "Authentication",
      "Custom Code Score": 80,
      "Library Score": 87,
      "Overall Score": 80,
    },
    {
      "Assignment Group": "Login",
      "Custom Code Score": 65,
      "Library Score": 45,
      "Overall Score": 60,
    },
    {
      "Assignment Group": "SSO",
      "Custom Code Score": 60,
      "Library Score": 78,
      "Overall Score": 65,
    },
  ],
};

export default issuesJson;
